# Generated by Django 2.0.5 on 2019-03-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Zaplanirovana', 'Zaplanirovana'), ('Vypolneno', 'Vypolneno'), ('Otmeneno', 'Otmeneno')], max_length=100)),
            ],
        ),
    ]
