# Generated by Django 2.0.5 on 2019-03-10 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Zadacha',
        ),
        migrations.RenameField(
            model_name='zadacha',
            old_name='title',
            new_name='status',
        ),
    ]
