# Generated by Django 2.0.5 on 2019-03-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20190310_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='zadacha',
            name='Opisanie',
            field=models.CharField(default=415, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zadacha',
            name='status',
            field=models.CharField(choices=[(('Zaplanirovana',), 'Zaplanirovana'), (('Vypolneno',), 'Vypolneno'), (('Otmeneno',), 'Otmeneno')], max_length=100),
        ),
    ]
