# Generated by Django 2.0.5 on 2019-03-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20190310_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zadacha',
            name='status',
            field=models.CharField(choices=[(('Zaplanirovana',), 'Zaplanirovana'), (('Vypolneno',), 'Vypolneno'), (('Otmeneno',), 'Otmeneno')], max_length=100),
        ),
    ]
