# Generated by Django 2.0.5 on 2019-03-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20190310_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zadacha',
            name='status',
            field=models.CharField(choices=[(('Zaplanirovana',), 'Zaplanirovana'), (('Vypolneno',), 'Vypolneno'), ('Otmeneno', 'Otmeneno')], max_length=100),
        ),
    ]
