# Generated by Django 2.0.5 on 2019-03-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20190310_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='zadacha',
            name='date_pub',
            field=models.DateTimeField(auto_now_add=True, default=54153),
            preserve_default=False,
        ),
    ]
